/*
 * Principale.java
 *
 * Created on 18 novembre 2006, 15.35
 */
package it.unina.lbd.lbd2012;

/**
 * Frame principale.
 *
 * @author Massimo
 */
public class Principale extends javax.swing.JFrame {

    /**
     * Creates new form Principale
     */
    public Principale() {
        initComponents();
        Login l;
        l = new Login(this, true);
        l.setVisible(true);
        if (l.getBottonePremuto() == Login.PREMUTO_ANNULLA) {
            dispose();
        } else {
            setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bNuovoLabirinto = new javax.swing.JButton();
        bCercaLabirinto = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        miLogin = new javax.swing.JMenuItem();
        miEsci = new javax.swing.JMenuItem();
        menFunzioni = new javax.swing.JMenu();
        miMarca = new javax.swing.JMenuItem();
        miModello = new javax.swing.JMenuItem();
        miAllestimento = new javax.swing.JMenuItem();
        miCaratteristica = new javax.swing.JMenuItem();
        menAiuto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laboratorio di basi di dati");

        bNuovoLabirinto.setText("Nuovo labirinto");
        bNuovoLabirinto.setFocusable(false);
        bNuovoLabirinto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNuovoLabirinto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNuovoLabirinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuovoLabirintoActionPerformed(evt);
            }
        });

        bCercaLabirinto.setText("Cerca Labirinto");
        bCercaLabirinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCercaLabirintoActionPerformed(evt);
            }
        });

        menFile.setText("File");

        miLogin.setText("Login");
        miLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoginActionPerformed(evt);
            }
        });
        menFile.add(miLogin);

        miEsci.setText("Esci");
        miEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEsciActionPerformed(evt);
            }
        });
        menFile.add(miEsci);

        jMenuBar.add(menFile);

        menFunzioni.setText("Funzioni");

        miMarca.setText("Marca");
        miMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMarcaActionPerformed(evt);
            }
        });
        menFunzioni.add(miMarca);

        miModello.setText("Modello");
        miModello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModelloActionPerformed(evt);
            }
        });
        menFunzioni.add(miModello);

        miAllestimento.setText("Allestimento");
        miAllestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAllestimentoActionPerformed(evt);
            }
        });
        menFunzioni.add(miAllestimento);

        miCaratteristica.setText("Caratteristica");
        miCaratteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCaratteristicaActionPerformed(evt);
            }
        });
        menFunzioni.add(miCaratteristica);

        jMenuBar.add(menFunzioni);

        menAiuto.setMnemonic('1');
        menAiuto.setText("Aiuto");
        jMenuBar.add(menAiuto);

        setJMenuBar(jMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(bNuovoLabirinto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(70, 70, 70)
                .add(bCercaLabirinto)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {bCercaLabirinto, bNuovoLabirinto}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(bCercaLabirinto)
                    .add(bNuovoLabirinto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {bCercaLabirinto, bNuovoLabirinto}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCaratteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCaratteristicaActionPerformed
    }//GEN-LAST:event_miCaratteristicaActionPerformed

    private void miEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEsciActionPerformed
        dispose();
    }//GEN-LAST:event_miEsciActionPerformed

    private void miAllestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAllestimentoActionPerformed
    }//GEN-LAST:event_miAllestimentoActionPerformed

    private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
        Login l;
        l = new Login(this, true);
        l.setVisible(true);
        if (l.getBottonePremuto() == Login.PREMUTO_ANNULLA) {
            dispose();
        }
    }//GEN-LAST:event_miLoginActionPerformed

    private void miModelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModelloActionPerformed
    }//GEN-LAST:event_miModelloActionPerformed

    private void miMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMarcaActionPerformed
    }//GEN-LAST:event_miMarcaActionPerformed

    private void bNuovoLabirintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuovoLabirintoActionPerformed
        int modalita_nuovo = 1;
        labirinto(modalita_nuovo);
    }//GEN-LAST:event_bNuovoLabirintoActionPerformed

    private void bCercaLabirintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCercaLabirintoActionPerformed
        Labirinto l;
        int modalita_cerca = 2;
        l = new Labirinto(modalita_cerca);
        l.eseguiQuery();
        l.setVisible(true);
    }//GEN-LAST:event_bCercaLabirintoActionPerformed

    private void labirinto(int modalita) {
        Labirinto l;
        l = new Labirinto(modalita);
        l.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Principale();

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCercaLabirinto;
    private javax.swing.JButton bNuovoLabirinto;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu menAiuto;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menFunzioni;
    private javax.swing.JMenuItem miAllestimento;
    private javax.swing.JMenuItem miCaratteristica;
    private javax.swing.JMenuItem miEsci;
    private javax.swing.JMenuItem miLogin;
    private javax.swing.JMenuItem miMarca;
    private javax.swing.JMenuItem miModello;
    // End of variables declaration//GEN-END:variables
}
